# Air configuration for Gin project

cmd = "go run cmd/server/main.go"
root = "."
include_dir = ["."]
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]

[build]
    bin = "tmp/main.exe"
    cmd = "go build -o tmp/main.exe ./cmd/server"
    stop_on_error = true
    delay = 300

[log]
    time = true

[misc]
    clean_on_exit = true
