FROM golang:1.24-alpine AS builder

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o Smradity ./cmd/server

FROM alpine:3.19

WORKDIR /root/

COPY --from=builder /app/Smradity .

CMD ["./Smradity"]